version: '3'

services: 
  endpoint:
    build: ./src
    env_file: ./database.env
    volumes:
      - ./src:/usr/src/app
    ports:
        - 5000:80
    depends_on:
       -  database
  database:
    build:
      context: ./src
      dockerfile: Dockerfile-db
    restart: always
    env_file: ./database.env